//AUTH ACTIONS
export const SWITCH_AUTH_MODE = 'SWITCH_AUTH_MODE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

export const AUTH_BTN_CLICK = 'AUTH_BTN_CLICK'
export const BACKDROP_CLICK = 'CLOSE_FORM'

//TO-DO-LIST ACTIONS
export const UPDATE_ID_SUCCESS = 'UPDATE_ID_SUCCESS'
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS'
export const POST_TASK_FAIL = 'POST_TASK_FAIL'

export const PUT_TASK_SUCCESS = 'PUT_TASK_SUCCESS'
export const PUT_TASK_FAIL = 'PUT_TASK_FAIL'

export const DELETE_OR_FINISH_TASK_FAIL = 'DELETE_OR_FINISH_TASK_FAIL'
export const DELETE_OR_FINISH_TASK_SUCCESS = 'DELETE_OR_FINISH_TASK_SUCCESS'

export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'


