//AUTH ACTIONS
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const SWITCH_AUTH_MODE = 'SWITCH_AUTH_MODE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_BTN_CLICK = 'AUTH_BTN_CLICK'
export const CLOSE_FORM = 'CLOSE_FORM'



//TO-DO-LIST ACTIONS
export const ADD_TASK = 'ADD_TASK'
export const FINISH_OR_DELETE_TASK = 'FINISH_OR_DELETE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'

export const POST_TASKS_START = 'POST_POST_TASKS_START'
export const POST_TASKS_SUCCESS = 'POST_TASKS_SUCCESS'
export const POST_TASKS_FAIL = 'POST_TASKS_FAIL'

export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL'


